### ISSUE TITLE
Read HuBMAP data/metadata for selection of channels for tissue segmentation

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/phenocycler-pipeline#2]
The MIBI segmentation code reads a static YAML file in the repository for selection of nuclear and cell membrane segmentation channels -- read this from each dataset instead.

**Comment by mruffalo** [comment]
Need an example `channels.csv` file; working on getting one from UPenn.

**Comment by NickEngland** [comment]
[16-11_Scan1.ome-tiff.channels.csv](https://github.com/hubmapconsortium/phenocycler-pipeline/files/15235966/16-11_Scan1.ome-tiff.channels.csv)

**Comment by NickEngland** [comment]
This is implemented in pull request.
