### ISSUE TITLE
TiffData elements being removed and added puts them after Plane. They need to be before Plane instead.

### ISSUE THREAD

**Issue by NickEngland** [hubmapconsortium/phenocycler-pipeline#3]
In the utils_ome.py file

Plane elements need to be moved to be after the TiffData elements as in OME the TiffData has to come before the Plane elements.

Currently 

    remove_tiffdata(px_node)
    generate_and_add_new_tiffdata(px_node)

results in the TiffData moving to the end.

**Comment by mruffalo** [comment]
I'd hoped to be able to use `aicsimageio` entirely for creating valid OME-XML metadata, by modifying the attributes/metadata of an in-memory object, and relying on the `aicsimageio` package to create the OME-XML.

As per https://allencellmodeling.github.io/aicsimageio/aicsimageio.metadata.html#aicsimageio.metadata.utils.physical_pixel_sizes, though, `aicsimageio` still doesn't handle physical pixel size _units,_ so we need to (at very least) tweak the generated OME-XML. For ease of implementation, it's worth continuing to generate this ourselves.

**Comment by NickEngland** [comment]
This issue is now completed.
