### ISSUE TITLE
Change the logic to work on input on file names other than 3D_image_stack.ome.tiff

### ISSUE THREAD

**Issue by NickEngland** [hubmapconsortium/phenocycler-pipeline#4]
Currently the input file name is hardcoded to be 3D_image_stack.ome.tiff

It should be configurable in the yaml config file or auto-discover if there is only one tiff.

**Comment by mruffalo** [comment]
This repository will operate on QPTIFFs as input files, and should handle multiple QPTIFF files, writing the conversion of each to OME-TIFF (with valid metadata) and the paired segmentation mask.

**Comment by mruffalo** [comment]
Simplifying assumption for a first release of this pipeline: single QPTIFF with arbitrary base filename, with a matching channels CSV file with schema described in https://docs.google.com/spreadsheets/d/1JikzRNyDErspgPSel4P9Y6gx6N_mrAGIMDcJZd8TucA/edit#gid=0 .

**Comment by NickEngland** [comment]
This is now implemented to work for a single QPTIFF file with arbitrary filename.
